version: "3"

services: 
  server:
    container_name: server
    image: nginx
    ports:
      - 80:80
    links:
      - php
    volumes:
      - ./:/app
      - ./server/nginx.conf:/etc/nginx/nginx.conf

  database:
    image: mariadb
    container_name: database
    ports:
      - 3306:3306
    environment:
      MARIADB_USER: root
      MARIADB_DATABASE: MaisonDatty
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
      MARIADB_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - ./api/DB:/var/lib/mysql

  php:
    build:
      context: ./api
    container_name: phpcgi
    volumes:
      - .:/app
    expose:
      - 9000

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=database